# Generated by Django 3.0.7 on 2020-06-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BikeHouse',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('cc', models.IntegerField(max_length=3)),
                ('model', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bike_house.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bike_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_house.BikeHouse')),
            ],
        ),
    ]
