# Generated by Django 3.0.7 on 2020-06-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikehouse',
            name='cc',
            field=models.IntegerField(),
        ),
    ]
